language: python
python:
  - "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  #- "nightly"
# command to install dependencies
install:
  #- "pip install ."
  - "pip install -r requirements.txt"
  - "pip install git+https://github.com/snyderp/pygmail"
# command to run tests
script: nosetests
